// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg9DuXpCq6fUYPio_PDQsDUPVJmTTRsLU',
    appId: '1:229268993676:web:d7a1839c0173bda9f36da9',
    messagingSenderId: '229268993676',
    projectId: 'be-vision',
    authDomain: 'be-vision.firebaseapp.com',
    storageBucket: 'be-vision.firebasestorage.app',
    measurementId: 'G-4H22NZ5JCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgRtrXnWellE0PRIeu77k--2OLKH_DxKY',
    appId: '1:229268993676:android:33ba6f886c1ece06f36da9',
    messagingSenderId: '229268993676',
    projectId: 'be-vision',
    storageBucket: 'be-vision.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3ldS_jdnBzui_2unvC1xV7-FkWCHQbk4',
    appId: '1:229268993676:ios:fa2d5e4f96806d56f36da9',
    messagingSenderId: '229268993676',
    projectId: 'be-vision',
    storageBucket: 'be-vision.firebasestorage.app',
    iosBundleId: 'com.bevision.goexperts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3ldS_jdnBzui_2unvC1xV7-FkWCHQbk4',
    appId: '1:229268993676:ios:fa2d5e4f96806d56f36da9',
    messagingSenderId: '229268993676',
    projectId: 'be-vision',
    storageBucket: 'be-vision.firebasestorage.app',
    iosBundleId: 'com.bevision.goexperts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg9DuXpCq6fUYPio_PDQsDUPVJmTTRsLU',
    appId: '1:229268993676:web:be1b18876f952182f36da9',
    messagingSenderId: '229268993676',
    projectId: 'be-vision',
    authDomain: 'be-vision.firebaseapp.com',
    storageBucket: 'be-vision.firebasestorage.app',
    measurementId: 'G-NB3CBG4EWQ',
  );
}
